import type {
  AwsResource,
  Deployment,
  LogEntry,
  PipelineStage,
  ProjectConfig,
} from '../types/deployment';


export const projectConfig: ProjectConfig = {
  projectName: 'E10 CI/CD',
  projectTagline: 'Deployment Control Center',
  repository: 'Guruprasad-Bhosale/ecr-cicd-demo',
  branch: 'main',
  commitSha: '408a8d0b2f5c1d3e4a9b6c8e7f1a2b3c4d5e6f7a',
  shortSha: '408a8d0',
  awsAccount: '058264128244',
  awsRegion: 'ap-south-1',
  ecrRepository: 'dvops-flask-app',
  ecsCluster: 'flask-app-cluster',
  ecsService: 'flask-app-service',
  containerName: 'flask-app',
  containerPort: 5000,
  containerUser: 'appuser (UID 10001)',
  authMethod: 'GitHub OIDC (AssumeRoleWithWebIdentity)',
  albName: 'flask-app-alb',
  healthCheckPath: '/health',
};

export const pipelineStages: PipelineStage[] = [
  {
    id: 'stage-test',
    name: 'Quality Gate',
    jobName: 'test',
    trigger: 'push / pull_request',
    purpose: 'Ruff code linting and Pytest unit test suite execution',
    status: 'PASSED',
    statusDetails: '4/4 unit tests passing • 0 lint errors',
    iconType: 'test',
    executionTime: '12s',
  },
  {
    id: 'stage-build',
    name: 'Docker Build',
    jobName: 'build-and-push',
    trigger: 'push (main)',
    dependency: 'needs: test',
    purpose: 'Build hardened non-root container (python:3.11-slim, port 5000)',
    status: 'PASSED',
    statusDetails: 'Multi-stage build • Non-root user 10001',
    iconType: 'build',
    executionTime: '28s',
  },
  {
    id: 'stage-oidc',
    name: 'OIDC Authentication',
    jobName: 'build-and-push',
    trigger: 'push (main)',
    dependency: 'build step',
    purpose: 'Assume github-actions-ecr-role via cryptographic JWT handshake',
    status: 'PASSED',
    statusDetails: 'Zero static keys • Federated STS authentication',
    iconType: 'oidc',
    executionTime: '3s',
  },
  {
    id: 'stage-ecr',
    name: 'Amazon ECR Publish',
    jobName: 'build-and-push',
    trigger: 'push (main)',
    dependency: 'oidc auth',
    purpose: 'Publish immutable Git SHA tag and latest tag to AWS registry',
    status: 'PASSED',
    statusDetails: 'Tagged: 408a8d0 & latest • AES256 • scanOnPush',
    iconType: 'ecr',
    executionTime: '15s',
  },
  {
    id: 'stage-ecs',
    name: 'ECS Task Registration',
    jobName: 'deploy-ecs',
    trigger: 'push (main)',
    dependency: 'needs: build-and-push',
    purpose: 'Register new task definition revision and update ECS service',
    status: 'BLOCKED',
    statusDetails: 'Awaiting AWS IAM Administrator role provisioning',
    iconType: 'ecs',
  },
  {
    id: 'stage-stability',
    name: 'ECS Stability Wait',
    jobName: 'deploy-ecs',
    trigger: 'push (main)',
    dependency: 'task update',
    purpose: 'Poll AWS ECS steady state (aws ecs wait services-stable)',
    status: 'BLOCKED',
    statusDetails: 'Awaiting ECS Fargate cluster provisioning',
    iconType: 'stability',
  },
  {
    id: 'stage-alb',
    name: 'ALB Live Smoke Test',
    jobName: 'smoke-test',
    trigger: 'push (main)',
    dependency: 'needs: deploy-ecs',
    purpose: 'Layer 7 HTTP health verification against ALB public DNS',
    status: 'BLOCKED',
    statusDetails: 'Awaiting ALB & Target Group provisioning',
    iconType: 'alb',
  },
];

export const awsResources: AwsResource[] = [
  {
    id: 'res-ecr',
    name: 'dvops-flask-app',
    type: 'Amazon Elastic Container Registry (ECR)',
    region: 'ap-south-1',
    status: 'ACTIVE',
    statusMessage: 'Repository verified active with published container images',
    details: [
      { label: 'Registry URI', value: '058264128244.dkr.ecr.ap-south-1.amazonaws.com/dvops-flask-app' },
      { label: 'Encryption', value: 'AES256 Server-Side' },
      { label: 'Scan On Push', value: 'Enabled' },
      { label: 'Active Digest', value: 'sha256:268a92c03e2fbdf11fff6829fef51a5a236f1098db449ef23ec0dabc01bb9910' },
    ],
  },
  {
    id: 'res-oidc',
    name: 'github-actions-ecr-role',
    type: 'AWS IAM OIDC Identity Provider & Role',
    region: 'Global / ap-south-1',
    status: 'PROVISIONING_REQUIRED',
    statusMessage: 'IAM role and OIDC trust policy defined; awaiting AWS Administrator execution',
    details: [
      { label: 'Role ARN', value: 'arn:aws:iam::058264128244:role/github-actions-ecr-role' },
      { label: 'Federated Provider', value: 'token.actions.githubusercontent.com' },
      { label: 'Trust Constraint', value: 'repo:Guruprasad-Bhosale/ecr-cicd-demo:ref:refs/heads/main' },
      { label: 'Audience', value: 'sts.amazonaws.com' },
    ],
  },
  {
    id: 'res-ecs-cluster',
    name: 'flask-app-cluster',
    type: 'AWS ECS Fargate Cluster',
    region: 'ap-south-1',
    status: 'PROVISIONING_REQUIRED',
    statusMessage: 'Defined in Terraform (infra/ecs-fargate.tf); requires Terraform apply',
    details: [
      { label: 'Launch Type', value: 'FARGATE (Serverless)' },
      { label: 'VPC', value: '10.0.0.0/16 (2 Multi-AZ Public Subnets)' },
      { label: 'Task Family', value: 'flask-app-task (256 CPU / 512 MB RAM)' },
      { label: 'Service', value: 'flask-app-service (Desired: 1, MinHealthy: 100%)' },
    ],
  },
  {
    id: 'res-alb',
    name: 'flask-app-alb',
    type: 'Application Load Balancer (ALB) & Target Group',
    region: 'ap-south-1',
    status: 'PROVISIONING_REQUIRED',
    statusMessage: 'Defined in Terraform; routes port 80 to container port 5000',
    details: [
      { label: 'Target Group', value: 'flask-app-tg (HTTP 5000, target_type = ip)' },
      { label: 'Health Check Route', value: '/health (HTTP 200 Matcher, 30s interval)' },
      { label: 'Listener', value: 'HTTP Port 80 -> Forward to Target Group' },
      { label: 'Security Group', value: 'Inbound 80 from Internet; Ingress to ECS 5000 only' },
    ],
  },
  {
    id: 'res-cloudwatch',
    name: '/ecs/flask-app',
    type: 'Amazon CloudWatch Log Group',
    region: 'ap-south-1',
    status: 'PROVISIONING_REQUIRED',
    statusMessage: 'Structured logging destination for Gunicorn unbuffered stdout/stderr',
    details: [
      { label: 'Log Stream Prefix', value: 'ecs' },
      { label: 'Retention Policy', value: '7 Days' },
      { label: 'Driver', value: 'awslogs' },
    ],
  },
];

export const deploymentHistory: Deployment[] = [
  {
    id: 'dep-36878516253',
    commitSha: '408a8d0b2f5c1d3e4a9b6c8e7f1a2b3c4d5e6f7a',
    shortSha: '408a8d0',
    commitMessage: 'feat(infra): add ECS Fargate Terraform architecture and deployment specifications',
    branch: 'main',
    imageUri: '058264128244.dkr.ecr.ap-south-1.amazonaws.com/dvops-flask-app:408a8d0',
    imageTag: '408a8d0',
    imageDigest: 'sha256:268a92c03e2fbdf11fff6829fef51a5a236f1098db449ef23ec0dabc01bb9910',
    environment: 'AWS ECS Fargate (ap-south-1)',
    status: 'BLOCKED',
    reason: 'AWS IAM Administrator provisioning required for github-actions-ecr-role',
    startedAt: '2026-10-01 20:20:28 UTC',
    duration: '45s',
    steps: [
      { name: 'Quality Gate (Ruff + Pytest)', status: 'PASSED', timestamp: '20:20:30', duration: '12s', details: '4/4 unit tests passed' },
      { name: 'Docker Build & Hardening', status: 'PASSED', timestamp: '20:20:42', duration: '28s', details: 'Non-root appuser:10001' },
      { name: 'GitHub OIDC AssumeRole', status: 'BLOCKED', timestamp: '20:21:10', duration: '5s', details: 'AccessDenied: Awaiting admin role creation' },
      { name: 'ECR Publication', status: 'NOT_EXECUTED', timestamp: '-', duration: '-', details: 'Skipped due to upstream blocker' },
      { name: 'ECS Task Revision', status: 'NOT_EXECUTED', timestamp: '-', duration: '-', details: 'Skipped' },
      { name: 'ALB Smoke Test', status: 'NOT_EXECUTED', timestamp: '-', duration: '-', details: 'Skipped' },
    ],
  },
  {
    id: 'dep-36874978373',
    commitSha: '53f0543a1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e',
    shortSha: '53f0543',
    commitMessage: 'test(ci): controlled test failure gate validation',
    branch: 'test-failure-gate',
    imageUri: '058264128244.dkr.ecr.ap-south-1.amazonaws.com/dvops-flask-app:53f0543',
    imageTag: '53f0543',
    imageDigest: 'Not Generated',
    environment: 'Validation Runner',
    status: 'FAILED',
    reason: 'Controlled unit test failure halted downstream image publication',
    startedAt: '2026-09-28 14:15:10 UTC',
    duration: '18s',
    steps: [
      { name: 'Quality Gate (Pytest)', status: 'FAILED', timestamp: '14:15:12', duration: '18s', details: 'Intentional assertion failure' },
      { name: 'Docker Build & Push', status: 'NOT_EXECUTED', timestamp: '-', duration: '-', details: 'Safely bypassed by CI failure gate' },
      { name: 'ECS Deployment', status: 'NOT_EXECUTED', timestamp: '-', duration: '-', details: 'Safely bypassed by CI failure gate' },
    ],
  },
  {
    id: 'dep-initial-ecr',
    commitSha: '000a8c1926f3d3785e47965aa4e9ce6bf6f89670',
    shortSha: '000a8c1',
    commitMessage: 'feat: initial Flask application and Docker container build',
    branch: 'main',
    imageUri: '058264128244.dkr.ecr.ap-south-1.amazonaws.com/dvops-flask-app:000a8c1',
    imageTag: '000a8c1',
    imageDigest: 'sha256:331027470dca8cdecba55aa5426e1e44927a3dcde7cce8d56f7016597552cd86',
    environment: 'Amazon ECR',
    status: 'PASSED',
    startedAt: '2026-09-28 12:02:38 UTC',
    duration: '1m 12s',
    steps: [
      { name: 'Quality Gate', status: 'PASSED', timestamp: '12:02:40', duration: '15s', details: 'Unit tests verified' },
      { name: 'Docker Build', status: 'PASSED', timestamp: '12:02:55', duration: '35s', details: 'Built python:3.11-slim' },
      { name: 'ECR Push', status: 'PASSED', timestamp: '12:03:30', duration: '20s', details: 'Pushed image to registry' },
    ],
  },
];

export const projectLogs: LogEntry[] = [
  { id: 'log-1', timestamp: '20:20:10.104', level: 'INFO', source: 'pipeline', message: 'Triggered GitHub Actions CI/CD workflow for commit 408a8d0 on branch main' },
  { id: 'log-2', timestamp: '20:20:12.350', level: 'INFO', source: 'pipeline', message: 'Ruff linter executed: 0 errors found across 4 files' },
  { id: 'log-3', timestamp: '20:20:15.820', level: 'INFO', source: 'pipeline', message: 'Pytest test suite executed: 4 passed, 0 failed in 0.10s' },
  { id: 'log-4', timestamp: '20:20:18.910', level: 'INFO', source: 'docker', message: 'Building Docker container: Stage 1 non-root user appuser (UID 10001)' },
  { id: 'log-5', timestamp: '20:20:35.400', level: 'INFO', source: 'docker', message: 'Docker image built successfully: tags [408a8d0, latest]' },
  { id: 'log-6', timestamp: '20:20:38.120', level: 'INFO', source: 'ecr', message: 'Queried target registry: 058264128244.dkr.ecr.ap-south-1.amazonaws.com/dvops-flask-app' },
  { id: 'log-7', timestamp: '20:20:41.210', level: 'WARN', source: 'pipeline', message: 'OIDC AssumeRoleWithWebIdentity: github-actions-ecr-role not found or trust policy pending' },
  { id: 'log-8', timestamp: '20:20:42.005', level: 'WARN', source: 'ecs', message: 'ECS Continuous Deployment paused: AWS IAM Administrator provisioning required' },
  { id: 'log-9', timestamp: '20:20:43.150', level: 'INFO', source: 'terraform', message: 'Terraform plan validated: 12 resources defined, 0 destructive changes pending' },
  { id: 'log-10', timestamp: '20:26:08.500', level: 'INFO', source: 'alb', message: 'Local runtime check: Flask WSGI running on http://127.0.0.1:5000 (GET /health -> 200 OK)' },
];
